[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.prod]
command = "cargo"
args = ["build", "--workspace", "--release", "--features", "prod"]

[tasks.run]
env = { API_KEY = "your_api_key_here" }
command = "cargo"
args = ["run", "--bin", "nova_cli", "--", "--base-url", "http://192.168.0.68:12340", "--model", "gpt-oss-120b", "run", "${@}"]

[tasks.chat]
env = { API_KEY = "your_api_key_here" }
command = "cargo"
args = ["run", "--bin", "nova_cli", "--", "--base-url", "http://192.168.0.68:12340", "--model", "gpt-oss-120b", "chat"]


[tasks.chat-gemma]
env = { API_KEY = "your" }
command = "cargo"
args = ["run", "--bin", "nova_cli", "--", "--base-url", "http://192.168.0.68:12340", "--model", "google/gemma-4-26B-A4B-it", "chat"]


[tasks.default]
alias = "prod"




[tasks.check]
description = "Run all checks: fmt, clippy, and tests"
dependencies = ["_check_fmt", "_check_clippy"]


[tasks._check_fmt]
command = "cargo"
args = ["fmt", "--all"]

[tasks._check_clippy]
command = "cargo"
args = ["clippy", "--workspace", "--", "-D", "warnings"]
