import fs from 'node:fs/promises';
import { watch } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const workspaceRoot = path.resolve(projectRoot, '..');
const registryPath = path.join(workspaceRoot, 'schemas', 'registry.json');
const generatedDir = path.join(projectRoot, 'src', 'generated');
const schemaTypesPath = path.join(generatedDir, 'schema-types.ts');
const schemaValidatorsPath = path.join(generatedDir, 'schema-validators.ts');
const barrelPath = path.join(generatedDir, 'generated-types.ts');
const watchMode = process.argv.includes('--watch');
const EXTRA_OUTBOUND_PAYLOADS = ['chat'];
const CUSTOM_OUTBOUND_VALIDATORS = {
  'chat.start': {
    type: 'object',
    required: ['sessionId'],
    properties: {
      sessionId: { type: 'string' },
    },
  },
  'chat.complete': {
    type: 'object',
    required: ['sessionId'],
    properties: {
      sessionId: { type: 'string' },
      output: { type: ['string', 'null'] },
      usage: {
        type: ['object', 'null'],
        properties: {
          inputTokens: { type: 'integer' },
          outputTokens: { type: 'integer' },
          cacheCreationInputTokens: { type: 'integer' },
          cacheReadInputTokens: { type: 'integer' },
        },
        required: ['inputTokens', 'outputTokens'],
      },
    },
  },
  'sessions.list': {
    type: 'object',
    properties: {},
  },
  'session.runtime': {
    type: 'object',
    required: ['sessionId'],
    properties: {
      sessionId: { type: 'string' },
    },
  },
  'session.runtimes': {
    type: 'object',
    properties: {},
  },
};

main().catch((error) => {
  console.error('[generate:schemas] failed:', error);
  process.exitCode = 1;
});

async function main() {
  await generateAll();

  if (!watchMode) {
    return;
  }

  console.log('[generate:schemas] watching schema files...');
  let timer;
  const rerun = () => {
    if (timer) {
      clearTimeout(timer);
    }
    timer = setTimeout(() => {
      generateAll().catch((error) => {
        console.error('[generate:schemas] watch rebuild failed:', error);
      });
    }, 150);
  };

  watch(path.dirname(registryPath), { recursive: true }, (_eventType, filename) => {
    if (typeof filename === 'string' && filename.endsWith('.json')) {
      rerun();
    }
  });
}

async function generateAll() {
  await assertFileExists(registryPath);

  const registry = JSON.parse(await fs.readFile(registryPath, 'utf8'));
  const schemas = await loadFrontendSchemas(registry);

  const schemaTypesContent = buildSchemaTypesFile(schemas);
  const schemaValidatorsContent = buildSchemaValidatorsFile(schemas);
  const barrelContent = buildBarrelFile();

  await fs.mkdir(generatedDir, { recursive: true });
  await writeIfChanged(schemaTypesPath, schemaTypesContent);
  await writeIfChanged(schemaValidatorsPath, schemaValidatorsContent);
  await writeIfChanged(barrelPath, barrelContent);
}

async function assertFileExists(filePath) {
  try {
    await fs.access(filePath);
  } catch {
    throw new Error(`schema registry not found: ${filePath}`);
  }
}

async function loadFrontendSchemas(registry) {
  const entries = Object.values(registry.types)
    .filter((entry) => entry && entry.frontend === true)
    .sort((left, right) => left.name.localeCompare(right.name));

  const result = [];
  for (const entry of entries) {
    const absolutePath = path.resolve(workspaceRoot, entry.path);
    const schema = JSON.parse(await fs.readFile(absolutePath, 'utf8'));
    result.push({
      entry,
      schema,
      constName: toConstName(entry.name),
    });
  }

  return result;
}

function buildSchemaTypesFile(schemas) {
  const parts = [
    '// This file is generated by `npm run generate:schemas`.',
    '// Do not edit manually.',
    '',
  ];

  for (const item of schemas) {
    parts.push(`export type ${item.entry.name} = ${renderType(item.schema, item.schema, new Set())};`);
    parts.push('');
  }

  return `${parts.join('\n').trimEnd()}\n`;
}

function buildSchemaValidatorsFile(schemas) {
  const gatewaySchema = schemas.find((item) => item.entry.name === 'GatewayMessage');
  const inboundEntries = schemas.filter((item) => typeof item.entry.messageType === 'string' && !isOutboundEntry(item.entry));
  const outboundEntries = schemas.filter((item) => typeof item.entry.messageType === 'string' && isOutboundEntry(item.entry));

  const referencedSchemas = uniqueBy(
    [gatewaySchema, ...inboundEntries, ...outboundEntries].filter(Boolean),
    (item) => item.entry.name,
  );

  const lines = [
    '// This file is generated by `npm run generate:schemas`.',
    '// Do not edit manually.',
    '',
    'export interface ValidationHint {',
    '  path: string;',
    '  expected: string;',
    '  got?: unknown;',
    '  message?: string;',
    '}',
    '',
    "export type EnvelopeHint = 'missing-payload' | 'missing-type' | 'not-an-object';",
    "export type EnvelopeMode = 'message-only' | 'payload-required';",
    '',
    'type JsonSchema = Record<string, unknown> | boolean;',
    'type Validator = (value: unknown, path: string) => ValidationHint[];',
    '',
    'const DEFAULT_ERROR_THRESHOLD = 5;',
    '',
  ];

  for (const item of referencedSchemas) {
    lines.push(`const ${item.constName}Schema = ${JSON.stringify(item.schema, null, 2)} as const;`);
    lines.push('');
  }

  lines.push(`const customOutboundSchemas = ${JSON.stringify(CUSTOM_OUTBOUND_VALIDATORS, null, 2)} as const;`);
  lines.push('');
  lines.push('const schemaValidatorCache = new WeakMap<object, Validator>();');
  lines.push('');

  if (gatewaySchema) {
    lines.push(`const gatewayMessageValidator = createValidator(${gatewaySchema.constName}Schema, ${gatewaySchema.constName}Schema);`);
  } else {
    lines.push('const gatewayMessageValidator = (_value: unknown, _path: string) => [];');
  }
  lines.push('');

  lines.push('const inboundPayloadValidators: Record<string, Validator> = {');
  for (const item of inboundEntries) {
    lines.push(`  ${JSON.stringify(item.entry.messageType)}: createValidator(${item.constName}Schema, ${item.constName}Schema),`);
  }
  lines.push('};');
  lines.push('');

  lines.push('const outboundPayloadValidators: Record<string, Validator> = {');
  for (const item of outboundEntries) {
    lines.push(`  ${JSON.stringify(item.entry.messageType)}: createValidator(${item.constName}Schema, ${item.constName}Schema),`);
  }
  lines.push('  ...Object.fromEntries(Object.entries(customOutboundSchemas).map(([type, schema]) => [type, createValidator(schema, schema)])),');
  lines.push('};');
  lines.push('');

  lines.push(
    'export class ProtocolErrorHandler {',
    '  private consecutiveErrors = 0;',
    '',
    '  constructor(private readonly threshold: number = DEFAULT_ERROR_THRESHOLD) {}',
    '',
    '  record(): number {',
    '    this.consecutiveErrors += 1;',
    '    return this.consecutiveErrors;',
    '  }',
    '',
    '  reset(): void {',
    '    this.consecutiveErrors = 0;',
    '  }',
    '',
    '  exceeded(): boolean {',
    '    return this.consecutiveErrors > this.threshold;',
    '  }',
    '}',
    '',
    'export function validateEnvelope(message: unknown, modes: EnvelopeMode[] = [\'payload-required\']): EnvelopeHint[] {',
    '  if (!isRecord(message)) {',
    "    return ['not-an-object'];",
    '  }',
    '',
    '  const hints: EnvelopeHint[] = [];',
    '  if (typeof message.type !== \"string\" || message.type.length === 0) {',
    "    hints.push('missing-type');",
    '  }',
    '',
    '  const payloadOptional = modes.includes(\'message-only\');',
    '  if (!payloadOptional && !(\'payload\' in message)) {',
    "    hints.push('missing-payload');",
    '  }',
    '',
    '  return hints;',
    '}',
    '',
    'export function validateGatewayMessage(message: unknown): ValidationHint[] {',
    "  return gatewayMessageValidator(message, '$');",
    '}',
    '',
    'export function validateInboundPayload(type: string, payload: unknown): ValidationHint[] {',
    '  const validator = inboundPayloadValidators[type];',
    '  return validator ? validator(payload, type) : [];',
    '}',
    '',
    'export function validateOutboundPayload(type: string, payload: unknown): ValidationHint[] {',
    '  const validator = outboundPayloadValidators[type];',
    '  return validator ? validator(payload, type) : [];',
    '}',
    '',
    'function createValidator(schema: JsonSchema, rootSchema: JsonSchema): Validator {',
    '  if (typeof schema !== \"object\" || schema === null) {',
    '    return () => [];',
    '  }',
    '',
    '  const cached = schemaValidatorCache.get(schema);',
    '  if (cached) {',
    '    return cached;',
    '  }',
    '',
    '  const validator: Validator = (value, path) => validateWithSchema(schema, rootSchema, value, path);',
    '  schemaValidatorCache.set(schema, validator);',
    '  return validator;',
    '}',
    '',
    'function validateWithSchema(schema: JsonSchema, rootSchema: JsonSchema, value: unknown, path: string): ValidationHint[] {',
    '  if (schema === true) {',
    '    return [];',
    '  }',
    '',
    '  if (schema === false) {',
    "    return [{ path, expected: 'never', got: value }];",
    '  }',
    '',
    '  if (typeof schema !== \"object\" || schema === null) {',
    '    return [];',
    '  }',
    '',
    '  if (typeof schema.$ref === \"string\") {',
    '    const resolved = resolveRef(rootSchema, schema.$ref);',
    '    return resolved ? validateWithSchema(resolved, rootSchema, value, path) : [];',
    '  }',
    '',
    '  if (Array.isArray(schema.enum)) {',
    '    return schema.enum.some((item) => deepEqual(item, value))',
    '      ? []',
    "      : [{ path, expected: `one of ${schema.enum.map((item) => JSON.stringify(item)).join(', ')}`, got: value }];",
    '  }',
    '',
    '  if (Object.prototype.hasOwnProperty.call(schema, \"const\")) {',
    '    return deepEqual(schema.const, value)',
    '      ? []',
    "      : [{ path, expected: JSON.stringify(schema.const), got: value }];",
    '  }',
    '',
    '  if (Array.isArray(schema.anyOf)) {',
    '    return validateUnion(schema.anyOf, rootSchema, value, path, \"anyOf\");',
    '  }',
    '',
    '  if (Array.isArray(schema.oneOf)) {',
    '    return validateUnion(schema.oneOf, rootSchema, value, path, \"oneOf\");',
    '  }',
    '',
    '  if (Array.isArray(schema.allOf)) {',
    '    return schema.allOf.flatMap((item) => validateWithSchema(item, rootSchema, value, path));',
    '  }',
    '',
    '  const typeErrors = validateType(schema.type, value, path);',
    '  if (typeErrors.length > 0) {',
    '    return typeErrors;',
    '  }',
    '',
    '  if (schema.type === \"object\" || (!schema.type && (schema.properties || schema.required))) {',
    '    return validateObjectSchema(schema, rootSchema, value, path);',
    '  }',
    '',
    '  if (schema.type === \"array\") {',
    '    return validateArraySchema(schema, rootSchema, value, path);',
    '  }',
    '',
    '  if (schema.type === \"integer\" || schema.type === \"number\") {',
    '    return validateNumberSchema(schema, value, path);',
    '  }',
    '',
    '  if (Array.isArray(schema.type)) {',
    '    if (schema.type.includes(\"object\") && isRecord(value)) {',
    '      return validateObjectSchema(schema, rootSchema, value, path);',
    '    }',
    '    if (schema.type.includes(\"array\") && Array.isArray(value)) {',
    '      return validateArraySchema(schema, rootSchema, value, path);',
    '    }',
    '    if ((schema.type.includes(\"integer\") || schema.type.includes(\"number\")) && typeof value === \"number\") {',
    '      return validateNumberSchema(schema, value, path);',
    '    }',
    '  }',
    '',
    '  return [];',
    '}',
    '',
    'function validateUnion(schemas: JsonSchema[], rootSchema: JsonSchema, value: unknown, path: string, label: string): ValidationHint[] {',
    '  const variants = schemas.map((item) => validateWithSchema(item, rootSchema, value, path));',
    '  if (variants.some((errors) => errors.length === 0)) {',
    '    return [];',
    '  }',
    "  return [{ path, expected: label, got: value, message: variants[0]?.[0]?.message }];",
    '}',
    '',
    'function validateObjectSchema(schema: Record<string, unknown>, rootSchema: JsonSchema, value: unknown, path: string): ValidationHint[] {',
    '  if (!isRecord(value)) {',
    "    return [{ path, expected: 'object', got: value }];",
    '  }',
    '',
    '  const hints: ValidationHint[] = [];',
    '  const properties = isRecord(schema.properties) ? schema.properties : {};',
    '  const required = Array.isArray(schema.required) ? schema.required : [];',
    '  for (const key of required) {',
    '    if (!(key in value)) {',
    "      hints.push({ path: joinPath(path, String(key)), expected: 'present', got: undefined, message: 'missing required field' });",
    '    }',
    '  }',
    '',
    '  for (const [key, propertySchema] of Object.entries(properties)) {',
    '    if (!(key in value) || value[key] === undefined) {',
    '      continue;',
    '    }',
    '    hints.push(...validateWithSchema(propertySchema as JsonSchema, rootSchema, value[key], joinPath(path, key)));',
    '  }',
    '',
    '  if (schema.additionalProperties === false) {',
    '    for (const key of Object.keys(value)) {',
    '      if (!(key in properties)) {',
    "        hints.push({ path: joinPath(path, key), expected: 'no additional properties', got: value[key] });",
    '      }',
    '    }',
    '  } else if (typeof schema.additionalProperties === \"object\" && schema.additionalProperties !== null) {',
    '    for (const key of Object.keys(value)) {',
    '      if (!(key in properties)) {',
    '        hints.push(...validateWithSchema(schema.additionalProperties as JsonSchema, rootSchema, value[key], joinPath(path, key)));',
    '      }',
    '    }',
    '  }',
    '',
    '  return hints;',
    '}',
    '',
    'function validateArraySchema(schema: Record<string, unknown>, rootSchema: JsonSchema, value: unknown, path: string): ValidationHint[] {',
    '  if (!Array.isArray(value)) {',
    "    return [{ path, expected: 'array', got: value }];",
    '  }',
    '',
    '  if (!schema.items) {',
    '    return [];',
    '  }',
    '',
    '  return value.flatMap((item, index) => validateWithSchema(schema.items as JsonSchema, rootSchema, item, joinPath(path, String(index))));',
    '}',
    '',
    'function validateNumberSchema(schema: Record<string, unknown>, value: unknown, path: string): ValidationHint[] {',
    '  if (typeof value !== \"number\" || Number.isNaN(value)) {',
    "    return [{ path, expected: schema.type === 'integer' ? 'integer' : 'number', got: value }];",
    '  }',
    '',
    '  if (schema.type === \"integer\" && !Number.isInteger(value)) {',
    "    return [{ path, expected: 'integer', got: value }];",
    '  }',
    '',
    '  if (typeof schema.minimum === \"number\" && value < schema.minimum) {',
    "    return [{ path, expected: `>= ${schema.minimum}`, got: value }];",
    '  }',
    '',
    '  return [];',
    '}',
    '',
    'function validateType(type: unknown, value: unknown, path: string): ValidationHint[] {',
    '  if (type === undefined) {',
    '    return [];',
    '  }',
    '',
    '  if (Array.isArray(type)) {',
    '    return type.some((item) => validateType(item, value, path).length === 0)',
    '      ? []',
    "      : [{ path, expected: type.join(' | '), got: value }];",
    '  }',
    '',
    '  switch (type) {',
    "    case 'null':",
    '      return value === null ? [] : [{ path, expected: \"null\", got: value }];',
    "    case 'string':",
    '      return typeof value === \"string\" ? [] : [{ path, expected: \"string\", got: value }];',
    "    case 'boolean':",
    '      return typeof value === \"boolean\" ? [] : [{ path, expected: \"boolean\", got: value }];',
    "    case 'number':",
    '      return typeof value === \"number\" && !Number.isNaN(value) ? [] : [{ path, expected: \"number\", got: value }];',
    "    case 'integer':",
    '      return typeof value === \"number\" && Number.isInteger(value) ? [] : [{ path, expected: \"integer\", got: value }];',
    "    case 'object':",
    '      return isRecord(value) ? [] : [{ path, expected: \"object\", got: value }];',
    "    case 'array':",
    '      return Array.isArray(value) ? [] : [{ path, expected: \"array\", got: value }];',
    '    default:',
    '      return [];',
    '  }',
    '}',
    '',
    'function resolveRef(rootSchema: JsonSchema, ref: string): JsonSchema | null {',
    '  if (!ref.startsWith(\"#/\") || typeof rootSchema !== \"object\" || rootSchema === null) {',
    '    return null;',
    '  }',
    '',
    '  const parts = ref.slice(2).split(\"/\");',
    '  let current: unknown = rootSchema;',
    '  for (const part of parts) {',
    '    if (!isRecord(current) || !(part in current)) {',
    '      return null;',
    '    }',
    '    current = current[part];',
    '  }',
    '',
    '  return (current as JsonSchema) ?? null;',
    '}',
    '',
    'function joinPath(base: string, segment: string): string {',
    '  return base === \"$\" ? `${base}.${segment}` : `${base}.${segment}`;',
    '}',
    '',
    'function isRecord(value: unknown): value is Record<string, unknown> {',
    '  return typeof value === \"object\" && value !== null && !Array.isArray(value);',
    '}',
    '',
    'function deepEqual(left: unknown, right: unknown): boolean {',
    '  return JSON.stringify(left) === JSON.stringify(right);',
    '}',
  );

  return `${lines.join('\n').trimEnd()}\n`;
}

function buildBarrelFile() {
  return `// This file is generated by \`npm run generate:schemas\`.
// Do not edit manually.

export * from './schema-types';
export * from './schema-validators';
`;
}

function isOutboundEntry(entry) {
  return entry.kind === 'request' || EXTRA_OUTBOUND_PAYLOADS.includes(entry.messageType);
}

function renderType(schema, rootSchema, seenRefs) {
  if (schema === true) {
    return 'unknown';
  }

  if (schema === false || !schema || typeof schema !== 'object') {
    return 'never';
  }

  if (typeof schema.$ref === 'string') {
    if (seenRefs.has(schema.$ref)) {
      return 'unknown';
    }

    const resolved = resolveSchemaRef(rootSchema, schema.$ref);
    if (!resolved) {
      return 'unknown';
    }

    const nextSeenRefs = new Set(seenRefs);
    nextSeenRefs.add(schema.$ref);
    return renderType(resolved, rootSchema, nextSeenRefs);
  }

  if (Object.prototype.hasOwnProperty.call(schema, 'const')) {
    return JSON.stringify(schema.const);
  }

  if (Array.isArray(schema.enum)) {
    return unique(schema.enum.map((item) => JSON.stringify(item))).join(' | ') || 'never';
  }

  if (Array.isArray(schema.anyOf)) {
    return unique(schema.anyOf.map((item) => renderType(item, rootSchema, seenRefs))).join(' | ') || 'unknown';
  }

  if (Array.isArray(schema.oneOf)) {
    return unique(schema.oneOf.map((item) => renderType(item, rootSchema, seenRefs))).join(' | ') || 'unknown';
  }

  if (Array.isArray(schema.allOf)) {
    return unique(schema.allOf.map((item) => renderType(item, rootSchema, seenRefs))).join(' & ') || 'unknown';
  }

  if (Array.isArray(schema.type)) {
    return unique(schema.type.map((item) => renderType({ ...schema, type: item }, rootSchema, seenRefs))).join(' | ') || 'unknown';
  }

  if (schema.type === 'null') {
    return 'null';
  }
  if (schema.type === 'string') {
    return 'string';
  }
  if (schema.type === 'boolean') {
    return 'boolean';
  }
  if (schema.type === 'number' || schema.type === 'integer') {
    return 'number';
  }
  if (schema.type === 'array') {
    const itemType = renderType(schema.items ?? true, rootSchema, seenRefs);
    return `Array<${itemType}>`;
  }
  if (schema.type === 'object' || schema.properties || schema.required) {
    return renderObjectType(schema, rootSchema, seenRefs);
  }

  return 'unknown';
}

function renderObjectType(schema, rootSchema, seenRefs) {
  const properties = isPlainObject(schema.properties) ? schema.properties : {};
  const required = new Set(Array.isArray(schema.required) ? schema.required : []);
  const members = Object.entries(properties).map(([name, childSchema]) => {
    const optional = required.has(name) ? '' : '?';
    return `${renderPropertyName(name)}${optional}: ${renderType(childSchema, rootSchema, seenRefs)};`;
  });

  if (schema.additionalProperties && schema.additionalProperties !== false) {
    const additionalType = schema.additionalProperties === true
      ? 'unknown'
      : renderType(schema.additionalProperties, rootSchema, seenRefs);
    members.push(`[key: string]: ${additionalType};`);
  }

  if (members.length === 0) {
    return 'Record<string, unknown>';
  }

  return `{ ${members.join(' ')} }`;
}

function renderPropertyName(name) {
  return /^[$A-Z_a-z][$\w]*$/.test(name) ? name : JSON.stringify(name);
}

function resolveSchemaRef(rootSchema, ref) {
  if (!ref.startsWith('#/')) {
    return null;
  }

  const parts = ref.slice(2).split('/');
  let current = rootSchema;
  for (const part of parts) {
    if (!isPlainObject(current) || !(part in current)) {
      return null;
    }
    current = current[part];
  }
  return current;
}

function toConstName(name) {
  return `${name.replace(/[^A-Za-z0-9_$]/g, '_')}Generated`;
}

async function writeIfChanged(filePath, content) {
  const current = await fs.readFile(filePath, 'utf8').catch(() => null);
  if (current === content) {
    return;
  }

  await fs.writeFile(filePath, content, 'utf8');
}

function unique(values) {
  return [...new Set(values)];
}

function uniqueBy(values, getKey) {
  const seen = new Set();
  return values.filter((value) => {
    const key = getKey(value);
    if (seen.has(key)) {
      return false;
    }
    seen.add(key);
    return true;
  });
}

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
